### PR TITLE
 Convert libvirtd to use make-disk-image

### PR DESCRIPTION
**Pull request by teto**
This fixes #931 by reusing the
image builder of <nixpkgs/nixos/lib/make-disk-image.nix>. This image
builder produces nixos.qcow2 instead of disk.qcow2. This image is now
"baseless", so it obsoletes "qemu-img rebase". We can also remove our
special-case image builder libvirtd-image.nix as a whole.

follow up of https://github.com/NixOS/nixops/pull/1187 by @clefru

### CODE REVIEW

**Comment by AmineChikhaoui** [comment]
Doesn't seem to be working:
```
machine> [    3.345315] reboot: Power down
Traceback (most recent call last):
  File "/home/amine/src/nixops/scripts/nixops", line 245, in <module>
    args.op(args)
  File "/home/amine/src/nixops/nixops/script_defs.py", line 427, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/home/amine/src/nixops/nixops/deployment.py", line 1062, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/home/amine/src/nixops/nixops/deployment.py", line 1051, in run_with_notify
    f()
  File "/home/amine/src/nixops/nixops/deployment.py", line 1062, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/home/amine/src/nixops/nixops/deployment.py", line 999, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/home/amine/src/nixops/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/home/amine/src/nixops/nixops/deployment.py", line 972, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/01sj1ix5wgjfz2rqbz94rdx16z1cg7db-nixops-libvirtd/lib/python2.7/site-packages/nixopsvirtd/backends/libvirtd.py", line 163, in create
    self._prepare_storage_volume()
  File "/nix/store/01sj1ix5wgjfz2rqbz94rdx16z1cg7db-nixops-libvirtd/lib/python2.7/site-packages/nixopsvirtd/backends/libvirtd.py", line 195, in _prepare_storage_volume
    shutil.copyfile(os.path.join(temp_image_path, 'disk.qcow2'), temp_disk_path)
  File "/nix/store/gj7ma8b68qzdy383hhr78p0fdy7916mr-python-2.7.16/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/run/user/1000/nixops-tmphYwIzH/libvirtd-image-machine/disk.qcow2'
```

**Comment by eadwu** [comment]
Missing a chunk[1] from nixops/backends/libvirtd.py`. Resolves https://github.com/nix-community/nixops-libvirtd/issues/5. Working patch here [2].

[1] https://github.com/NixOS/nixops/pull/1187/files
[2] https://git.sr.ht/~eadwu/nixops/tree/master/patches/libvirtd.patch

**Comment by teto** [comment]
that should be fixed, thanks for spotting it.

**Comment by AmineChikhaoui** [comment]
Thanks !

**Pull request merged**
